(() => {
  const { register } = window.TokenCharacters
  const mix = (a, b, t) => a + (b - a) * t
  const ease = (t) => t * t * (3 - 2 * t)
  const commonPose = ({ phase, progress: p, startX, endX }, style = {}) => {
    const t = ease(p)
    if (phase === "resist") return { x: startX, y: -Math.sin(p * Math.PI * 3) * (style.resist ?? 2), rotate: -p * (style.lean ?? 10) }
    if (phase === "launch") return { x: mix(startX, startX - (style.launchX ?? 30), t), y: -Math.sin(t * Math.PI) * (style.launchY ?? 8), rotate: -(style.launchSpin ?? 55) * t }
    if (phase === "tumble") return { x: mix(startX - (style.launchX ?? 30), endX + (style.approach ?? 24), t), y: -Math.sin(t * Math.PI) * (style.arc ?? 7), rotate: -(style.spins ?? 1) * 360 * t - (style.launchSpin ?? 55) }
    const bounce = Math.sin(p * Math.PI)
    return { x: mix(endX + (style.approach ?? 24), endX, t), y: 2 - bounce * (style.bounce ?? 7), rotate: -(style.spins ?? 1) * 360 - (style.launchSpin ?? 55) + t * (style.launchSpin ?? 55), scaleX: 1 + bounce * .2, scaleY: 1 - bounce * .18 }
  }

  const baseCSS = (id, run, extra = "") => `
    .token-character[data-character="${id}"][data-phase="run"] .character-body{animation:${run} .42s steps(4) infinite;transform-origin:center bottom}
    .token-character[data-character="${id}"][data-phase="idle"] .character-body{animation:characterIdle 1.6s steps(4) infinite;transform-origin:center bottom}
    .token-character[data-character="${id}"][data-phase="resist"] .character-body{animation:characterResist .16s steps(2) infinite;transform-origin:center bottom}
    .token-character[data-character="${id}"][data-phase="launch"] .character-body{animation:characterLaunch .13s steps(2) infinite;transform-origin:center}
    .token-character[data-character="${id}"][data-phase="tumble"] .character-body{animation:characterTumble .24s steps(3) infinite;transform-origin:center}
    .token-character[data-character="${id}"][data-phase="land"] .character-body{animation:characterLand .2s steps(3) infinite;transform-origin:center bottom}
    ${extra}`

  register({
    id: "runner", name: "风火跑者", viewBox: "0 0 58 72", width: 31, height: 39,
    svg: `<g class="character-body"><g class="rear"><line data-bone="arm-b-upper"/><line data-bone="arm-b-lower"/><line data-bone="leg-b-upper"/><line data-bone="leg-b-lower"/></g><line data-bone="torso" class="core"/><g class="front"><line data-bone="arm-a-upper"/><line data-bone="arm-a-lower"/><line data-bone="leg-a-upper"/><line data-bone="leg-a-lower"/></g><circle class="head" r="8"/><rect class="eye" width="3" height="3"/></g>`,
    css: baseCSS("runner", "runnerBodyRun"),
    burstPose: (context) => commonPose(context, { launchX: 13, launchY: 4, arc: 6, spins: 1, approach: 31, bounce: 7 }),
    mounted(root) {
      root.characterParts = {
        bones: Object.fromEntries([...root.querySelectorAll("line[data-bone]")].map((line) => [line.dataset.bone, line])),
        head: root.querySelector(".head"),
        eye: root.querySelector(".eye"),
      }
    },
    render(root, { phase, progress, now }) {
      const { bones, head, eye } = root.characterParts
      const point = (origin, length, degrees) => { const angle = degrees * Math.PI / 180; return { x: origin.x + Math.sin(angle) * length, y: origin.y + Math.cos(angle) * length } }
      const line = (name, start, end) => { const item = bones[name]; item.setAttribute("x1", start.x); item.setAttribute("y1", start.y); item.setAttribute("x2", end.x); item.setAttribute("y2", end.y) }
      const gait = now / 115
      const idle = phase === "idle"
      const blown = !["idle", "run"].includes(phase)
      const overall = blown ? ({ resist: progress * .14, launch: .14 + progress * .11, tumble: .25 + progress * .57, land: .82 + progress * .18 })[phase] : 0
      const flight = idle || blown ? 0 : Math.abs(Math.sin(gait)) * 2.2
      const hip = { x: 27, y: 43 - flight }, shoulder = { x: blown && overall < .16 ? 36 : 32, y: 24 - flight }
      let legA = idle ? 5 : Math.sin(gait) * 52, legB = idle ? -7 : Math.sin(gait + Math.PI) * 52
      let bendA = idle ? 7 : 18 + 70 * Math.max(0, -Math.sin(gait)), bendB = idle ? 9 : 18 + 70 * Math.max(0, -Math.sin(gait + Math.PI))
      let armA = idle ? -8 : -legA * .72, armB = idle ? 10 : -legB * .72
      if (blown && overall < .16) { legA=16;legB=-18;bendA=6;bendB=9;armA=70;armB=52 }
      else if (blown && overall < .82) { const tumble=(overall-.16)/.66*Math.PI*4;legA=Math.sin(tumble)*68;legB=Math.sin(tumble+Math.PI)*68;bendA=34+38*(.5+.5*Math.cos(tumble));bendB=34+38*(.5+.5*Math.cos(tumble+Math.PI));armA=Math.sin(tumble+Math.PI/2)*82;armB=Math.sin(tumble-Math.PI/2)*82 }
      else if (blown) { legA=8;legB=-9;bendA=8;bendB=10;armA=-8;armB=10 }
      const kneeA=point(hip,17,legA),footA=point(kneeA,18,legA-bendA),kneeB=point(hip,17,legB),footB=point(kneeB,18,legB-bendB),elbowA=point(shoulder,13,armA),handA=point(elbowA,12,armA+(armA>=0?105:-105)),elbowB=point(shoulder,13,armB),handB=point(elbowB,12,armB+(armB>=0?105:-105))
      line("torso",shoulder,hip);line("leg-a-upper",hip,kneeA);line("leg-a-lower",kneeA,footA);line("leg-b-upper",hip,kneeB);line("leg-b-lower",kneeB,footB);line("arm-a-upper",shoulder,elbowA);line("arm-a-lower",elbowA,handA);line("arm-b-upper",shoulder,elbowB);line("arm-b-lower",elbowB,handB)
      head.setAttribute("cx",34);head.setAttribute("cy",12-flight);eye.setAttribute("x",37);eye.setAttribute("y",10-flight)
    },
  })

  register({ id:"rabbit",name:"缓存兔",svg:`<g class="character-body rabbit"><g class="ears"><path class="light" d="M38 23L35 3Q42 1 45 22Z"/><path class="main" d="M47 23L51 5Q58 8 53 28Z"/></g><ellipse class="main" cx="35" cy="39" rx="19" ry="14"/><circle class="light" cx="48" cy="29" r="11"/><circle class="eye-fill" cx="52" cy="27" r="2"/><circle class="flash" cx="16" cy="35" r="6"/><g class="feet"><path class="deep" d="M28 48H14Q10 54 31 54Z"/><path class="light" d="M45 48H34Q31 55 52 54Z"/></g></g>`,css:baseCSS("rabbit","rabbitRun",`.token-character[data-character="rabbit"] .ears{transform-origin:44px 22px}.token-character[data-character="rabbit"][data-phase="run"] .ears{animation:rabbitEars .5s steps(3) infinite}.token-character[data-character="rabbit"][data-phase="resist"] .ears{transform:rotate(-28deg)}.token-character[data-character="rabbit"][data-phase="launch"] .ears{animation:rabbitEarLaunch .13s steps(2) infinite}.token-character[data-character="rabbit"][data-phase="tumble"] .ears{animation:rabbitEarTumble .2s steps(3) infinite}.token-character[data-character="rabbit"][data-phase="land"] .ears{animation:rabbitEarLand .2s steps(3) infinite}`),burstPose:c=>{const p=commonPose(c,{launchX:34,launchY:11,arc:11,spins:.5,approach:22,bounce:9});if(c.phase==="resist"){p.scaleX=1.18;p.scaleY=.82}return p} })
  register({ id:"fox",name:"霓虹狐",svg:`<g class="character-body fox"><path class="tail main" d="M25 38Q5 16 4 41Q9 55 28 47Z"/><ellipse class="main" cx="36" cy="39" rx="19" ry="11"/><path class="light" d="M46 35L50 17L57 27L63 21L61 42Z"/><circle class="eye-fill" cx="56" cy="31" r="2"/><g class="legs stroke"><path d="M29 46L19 56"/><path d="M41 46L50 56"/></g><path class="flash no-stroke" d="M5 37Q8 49 17 50Q10 39 5 37"/></g>`,css:baseCSS("fox","foxRun",`.token-character[data-character="fox"] .tail{transform-origin:24px 39px}.token-character[data-character="fox"][data-phase="run"] .tail{animation:foxTail .4s steps(3) infinite}.token-character[data-character="fox"][data-phase="resist"] .tail{animation:foxTailBrace .16s steps(2) infinite}.token-character[data-character="fox"][data-phase="launch"] .tail{transform:rotate(38deg) scaleX(1.12)}.token-character[data-character="fox"][data-phase="tumble"] .tail{animation:foxTailTumble .18s steps(3) infinite}.token-character[data-character="fox"][data-phase="land"] .tail{animation:foxTailLand .2s steps(3) infinite}`),burstPose:c=>commonPose(c,{launchX:38,launchY:5,arc:4,spins:1.5,approach:28,bounce:5,lean:16}) })
  register({ id:"slime",name:"字节史莱姆",width:34,height:38,svg:`<g class="character-body slime"><path class="main" d="M12 52Q8 28 24 18Q32 8 42 19Q59 27 54 52Z"/><rect class="eye-fill" x="23" y="34" width="5" height="5"/><rect class="eye-fill" x="42" y="34" width="5" height="5"/><path class="stroke" d="M29 45H40"/><rect class="drop bright no-stroke" x="8" y="44" width="5" height="5"/></g>`,css:baseCSS("slime","slimeRun",`.token-character[data-character="slime"][data-phase="resist"] .character-body{animation:slimeResist .16s steps(2) infinite}.token-character[data-character="slime"][data-phase="launch"] .character-body{animation:slimeLaunch .13s steps(2) infinite}.token-character[data-character="slime"][data-phase="tumble"] .character-body{animation:slimeTumble .2s steps(3) infinite}.token-character[data-character="slime"][data-phase="land"] .character-body{animation:slimeLand .2s steps(3) infinite}`),burstPose:c=>{const p=commonPose(c,{launchX:24,launchY:10,arc:8,spins:0,approach:18,bounce:9});if(c.phase==="resist"||c.phase==="land"){p.scaleX=1.35;p.scaleY=.62;p.rotate=0}else if(c.phase==="launch"){p.scaleX=.72;p.scaleY=1.38}else if(c.phase==="tumble"){p.rotate=Math.sin(c.progress*Math.PI*6)*22;p.scaleX=.78+Math.abs(Math.sin(c.progress*Math.PI*4))*.35;p.scaleY=1.3-p.scaleX*.28}return p} })
  register({ id:"robot",name:"发条机器人",svg:`<g class="character-body robot"><g class="key stroke"><path d="M20 31H8V20"/><path d="M3 20H13"/></g><rect class="deep" x="21" y="27" width="27" height="24"/><rect class="light" x="24" y="8" width="25" height="20"/><rect class="eye-fill" x="29" y="16" width="4" height="4"/><rect class="eye-fill" x="41" y="16" width="4" height="4"/><path class="stroke" d="M36 8V3M31 3H41"/><g class="arms stroke"><path d="M23 33L14 43"/><path d="M47 33L56 25"/></g><path class="stroke" d="M28 50L23 59M42 50L49 59"/></g>`,css:baseCSS("robot","robotRun",`.token-character[data-character="robot"] .key{transform-origin:18px 31px}.token-character[data-character="robot"][data-phase="run"] .key{animation:robotKey .55s steps(4) infinite}.token-character[data-character="robot"][data-phase="resist"] .key{animation:robotKeyReverse .16s steps(2) infinite}.token-character[data-character="robot"][data-phase="launch"] .key{transform:rotate(-45deg)}.token-character[data-character="robot"][data-phase="tumble"] .key{animation:robotKeyFast .18s steps(4) infinite}.token-character[data-character="robot"][data-phase="land"] .key{animation:robotKeyLand .2s steps(3) infinite}`),burstPose:c=>{const p=commonPose(c,{launchX:22,launchY:2,arc:3,spins:2,approach:20,bounce:3,lean:6});if(c.phase==="tumble")p.rotate=Math.round(p.rotate/90)*90;return p} })
  register({ id:"ghost",name:"吞币幽灵",width:36,height:40,bottom:41,svg:`<g class="character-body ghost"><path class="main" d="M14 54V29Q15 10 34 10Q54 11 54 31V54L46 47L39 55L31 48L23 55Z"/><circle class="eye-fill" cx="29" cy="27" r="3"/><circle class="eye-fill" cx="42" cy="27" r="3"/><path class="mouth deep" d="M38 34L54 42L38 48Z"/></g>`,css:baseCSS("ghost","ghostRun",`.token-character[data-character="ghost"] .mouth{transform-origin:45px 41px}.token-character[data-character="ghost"][data-phase="run"] .mouth{animation:ghostMouth .32s steps(2) infinite}.token-character[data-character="ghost"][data-phase="resist"] .mouth{transform:scaleY(.2)}.token-character[data-character="ghost"][data-phase="launch"] .mouth{animation:ghostGasp .13s steps(2) infinite}.token-character[data-character="ghost"][data-phase="tumble"] .mouth{animation:ghostMouthTumble .2s steps(3) infinite}.token-character[data-character="ghost"][data-phase="land"] .mouth{animation:ghostMouthLand .2s steps(3) infinite}`),burstPose:c=>{const p=commonPose(c,{launchX:40,launchY:12,arc:13,spins:.25,approach:25,bounce:10,lean:22});p.opacity=c.phase==="tumble"?.55+Math.abs(Math.sin(c.progress*Math.PI*5))*.45:1;p.rotate+=Math.sin(c.overall*Math.PI*8)*8;return p} })
  register({ id:"dragon",name:"微型焰龙",width:39,height:39,bottom:42,svg:`<g class="character-body dragon"><path class="flame flash" d="M15 31L2 24L7 35L1 43L17 39Z"/><path class="main" d="M15 36Q27 20 44 30L59 23L54 38L62 45Q45 50 31 44Z"/><path class="wing light" d="M31 32L23 5L38 19L47 8L44 35Z"/><circle class="light" cx="49" cy="29" r="8"/><circle class="eye-fill" cx="53" cy="27" r="2"/><path class="stroke" d="M31 44L25 55M42 45L48 54"/></g>`,css:baseCSS("dragon","dragonRun",`.token-character[data-character="dragon"] .wing{transform-origin:32px 32px}.token-character[data-character="dragon"] .flame{transform-origin:15px 35px}.token-character[data-character="dragon"][data-phase="run"] .wing{animation:dragonWing .28s steps(2) infinite}.token-character[data-character="dragon"][data-phase="run"] .flame{animation:dragonFlame .2s steps(2) infinite}.token-character[data-character="dragon"][data-phase="resist"] .wing{animation:dragonWingBrace .16s steps(2) infinite}.token-character[data-character="dragon"][data-phase="resist"] .flame{transform:scaleX(1.3)}.token-character[data-character="dragon"][data-phase="launch"] .wing{transform:rotate(32deg) scaleY(.35)}.token-character[data-character="dragon"][data-phase="launch"] .flame{transform:scaleX(.3)}.token-character[data-character="dragon"][data-phase="tumble"] .wing{animation:dragonWingTumble .18s steps(3) infinite}.token-character[data-character="dragon"][data-phase="land"] .wing{animation:dragonWingLand .2s steps(3) infinite}`),burstPose:c=>{const p=commonPose(c,{launchX:42,launchY:11,arc:10,spins:1.25,approach:30,bounce:8,lean:22});if(c.phase==="land")p.rotate=-32+ease(c.progress)*32;return p} })
  register({ id:"ninja",name:"磁带忍者",width:35,height:41,svg:`<g class="character-body ninja"><path class="scarf main" d="M28 23L8 17L18 25L5 31L30 29Z"/><circle class="deep" cx="37" cy="17" r="10"/><path class="flash no-stroke" d="M30 15H46V20H30Z"/><rect class="eye-fill" x="41" y="16" width="3" height="2"/><path class="main" d="M28 27L44 25L48 43L33 46Z"/><path class="stroke" d="M33 44L18 54M42 43L55 52M31 30L18 38M44 31L53 24"/><path class="blade light" d="M53 37L58 41L63 37L59 43L63 48L57 45L52 49L55 43Z"/></g>`,css:baseCSS("ninja","ninjaRun",`.token-character[data-character="ninja"] .scarf{transform-origin:27px 25px}.token-character[data-character="ninja"] .blade{transform-origin:57px 43px}.token-character[data-character="ninja"][data-phase="run"] .scarf{animation:ninjaScarf .3s steps(3) infinite}.token-character[data-character="ninja"][data-phase="run"] .blade{animation:ninjaBlade .55s steps(6) infinite}.token-character[data-character="ninja"][data-phase="resist"] .scarf{transform:scaleX(1.25) rotate(-8deg)}.token-character[data-character="ninja"][data-phase="resist"] .blade{animation:ninjaBlade .2s steps(4) infinite}.token-character[data-character="ninja"][data-phase="launch"] .scarf{transform:scaleX(.45) rotate(25deg)}.token-character[data-character="ninja"][data-phase="tumble"] .scarf{animation:ninjaScarfTumble .18s steps(3) infinite}.token-character[data-character="ninja"][data-phase="tumble"] .blade{animation:ninjaBlade .16s steps(6) infinite}.token-character[data-character="ninja"][data-phase="land"] .scarf{animation:ninjaScarfLand .2s steps(3) infinite}`),burstPose:c=>{const p=commonPose(c,{launchX:52,launchY:8,arc:5,spins:2.5,approach:18,bounce:5,lean:18});if(c.phase==="tumble"){p.opacity=Math.floor(c.progress*10)%2?.55:1;p.x-=Math.floor(c.progress*6)%2*7}return p} })
  register({ id:"snail",name:"火箭蜗牛",width:40,height:38,svg:`<g class="character-body snail"><path class="jet light" d="M18 37L2 29L7 39L1 47L19 44Z"/><path class="main" d="M16 42Q30 48 49 44Q55 42 61 48H17Z"/><circle class="shell deep" cx="33" cy="34" r="16"/><path class="stroke shell-line" d="M33 25Q44 27 40 38Q36 45 28 39Q23 34 29 30"/><path class="stroke" d="M49 42L53 21M54 22L61 17M53 22L48 16"/><circle class="light" cx="61" cy="17" r="4"/><circle class="eye-fill" cx="62" cy="16" r="1.5"/></g>`,css:baseCSS("snail","snailRun",`.token-character[data-character="snail"] .shell,.token-character[data-character="snail"] .shell-line{transform-origin:33px 34px}.token-character[data-character="snail"] .jet{transform-origin:18px 39px}.token-character[data-character="snail"][data-phase="run"] .shell,.token-character[data-character="snail"][data-phase="run"] .shell-line{animation:snailShell .75s steps(8) infinite}.token-character[data-character="snail"][data-phase="run"] .jet{animation:snailJet .18s steps(2) infinite}.token-character[data-character="snail"][data-phase="resist"] .shell,.token-character[data-character="snail"][data-phase="resist"] .shell-line{animation:snailShellReverse .16s steps(3) infinite}.token-character[data-character="snail"][data-phase="resist"] .jet{animation:snailJetBrace .16s steps(2) infinite}.token-character[data-character="snail"][data-phase="launch"] .jet{transform:scaleX(.15)}.token-character[data-character="snail"][data-phase="tumble"] .shell,.token-character[data-character="snail"][data-phase="tumble"] .shell-line{animation:snailShellFast .16s steps(6) infinite}.token-character[data-character="snail"][data-phase="land"] .shell,.token-character[data-character="snail"][data-phase="land"] .shell-line{animation:snailShellLand .2s steps(3) infinite}`),burstPose:c=>{const p=commonPose(c,{launchX:18,launchY:3,arc:4,spins:3,approach:16,bounce:6,lean:5});if(c.phase==="resist")p.x-=Math.sin(c.progress*Math.PI*8)*4;return p} })
  register({ id:"cat",name:"量子猫",width:36,height:40,svg:`<g class="character-body cat"><g class="glitch"><path class="bright no-stroke" d="M23 28H48V47H23Z"/><path class="main no-stroke" d="M38 12L49 21L43 31H25L20 20L29 13L34 21Z"/></g><path class="tail stroke" d="M24 38Q7 29 12 17Q15 10 20 17"/><rect class="main" x="22" y="29" width="28" height="19"/><path class="light" d="M25 28L20 14L31 21L39 12L50 23L47 32Z"/><rect class="eye-fill" x="38" y="23" width="3" height="3"/><path class="stroke" d="M28 47L20 57M43 47L53 56"/></g>`,css:baseCSS("cat","catRun",`.token-character[data-character="cat"] .tail{transform-origin:23px 38px}.token-character[data-character="cat"] .glitch{opacity:0}.token-character[data-character="cat"][data-phase="run"] .tail{animation:catTail .38s steps(3) infinite}.token-character[data-character="cat"][data-phase="run"] .glitch{animation:catGlitch 1.4s steps(2) infinite}.token-character[data-character="cat"][data-phase="resist"] .tail{transform:rotate(-35deg)}.token-character[data-character="cat"][data-phase="launch"] .glitch{animation:catGlitchLaunch .13s steps(2) infinite}.token-character[data-character="cat"][data-phase="tumble"] .glitch{animation:catGlitchTumble .16s steps(3) infinite}.token-character[data-character="cat"][data-phase="land"] .glitch{animation:catGlitchLand .2s steps(3) infinite}`),burstPose:c=>{const p=commonPose(c,{launchX:44,launchY:9,arc:7,spins:.75,approach:25,bounce:8,lean:20});if(c.phase==="tumble"){p.x+=Math.sin(c.progress*Math.PI*8)*10;p.opacity=Math.floor(c.progress*12)%3===1?.45:1;p.filter="brightness(1.55)"}return p} })
})()
